// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: resource/resource/tx.proto

package resource

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName = "/resource.resource.Msg/UpdateParams"
	Msg_CreateFarm_FullMethodName   = "/resource.resource.Msg/CreateFarm"
	Msg_UpdateFarm_FullMethodName   = "/resource.resource.Msg/UpdateFarm"
	Msg_DeleteFarm_FullMethodName   = "/resource.resource.Msg/DeleteFarm"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	CreateFarm(ctx context.Context, in *MsgCreateFarm, opts ...grpc.CallOption) (*MsgCreateFarmResponse, error)
	UpdateFarm(ctx context.Context, in *MsgUpdateFarm, opts ...grpc.CallOption) (*MsgUpdateFarmResponse, error)
	DeleteFarm(ctx context.Context, in *MsgDeleteFarm, opts ...grpc.CallOption) (*MsgDeleteFarmResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateFarm(ctx context.Context, in *MsgCreateFarm, opts ...grpc.CallOption) (*MsgCreateFarmResponse, error) {
	out := new(MsgCreateFarmResponse)
	err := c.cc.Invoke(ctx, Msg_CreateFarm_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateFarm(ctx context.Context, in *MsgUpdateFarm, opts ...grpc.CallOption) (*MsgUpdateFarmResponse, error) {
	out := new(MsgUpdateFarmResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateFarm_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteFarm(ctx context.Context, in *MsgDeleteFarm, opts ...grpc.CallOption) (*MsgDeleteFarmResponse, error) {
	out := new(MsgDeleteFarmResponse)
	err := c.cc.Invoke(ctx, Msg_DeleteFarm_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	CreateFarm(context.Context, *MsgCreateFarm) (*MsgCreateFarmResponse, error)
	UpdateFarm(context.Context, *MsgUpdateFarm) (*MsgUpdateFarmResponse, error)
	DeleteFarm(context.Context, *MsgDeleteFarm) (*MsgDeleteFarmResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) CreateFarm(context.Context, *MsgCreateFarm) (*MsgCreateFarmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFarm not implemented")
}
func (UnimplementedMsgServer) UpdateFarm(context.Context, *MsgUpdateFarm) (*MsgUpdateFarmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFarm not implemented")
}
func (UnimplementedMsgServer) DeleteFarm(context.Context, *MsgDeleteFarm) (*MsgDeleteFarmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFarm not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateFarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateFarm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateFarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateFarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateFarm(ctx, req.(*MsgCreateFarm))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateFarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateFarm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateFarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateFarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateFarm(ctx, req.(*MsgUpdateFarm))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteFarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteFarm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteFarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DeleteFarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteFarm(ctx, req.(*MsgDeleteFarm))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resource.resource.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateFarm",
			Handler:    _Msg_CreateFarm_Handler,
		},
		{
			MethodName: "UpdateFarm",
			Handler:    _Msg_UpdateFarm_Handler,
		},
		{
			MethodName: "DeleteFarm",
			Handler:    _Msg_DeleteFarm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource/resource/tx.proto",
}
