swagger: '2.0'
info:
  title: HTTP API Console resource.resource
  name: ''
  description: ''
paths:
  /resource/resource/farm:
    get:
      operationId: Query_FarmAll
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              Farm:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uint64
                    animal:
                      type: string
                    plant:
                      type: string
                    creator:
                      type: string
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /resource/resource/farm/{id}:
    get:
      operationId: Query_Farm
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              Farm:
                type: object
                properties:
                  id:
                    type: string
                    format: uint64
                  animal:
                    type: string
                  plant:
                    type: string
                  creator:
                    type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: id
          in: path
          required: true
          type: string
          format: uint64
      tags:
        - Query
  /resource/resource/find_animal/{animal}:
    get:
      operationId: Query_FindAnimal
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              farm:
                type: object
                properties:
                  id:
                    type: string
                    format: uint64
                  animal:
                    type: string
                  plant:
                    type: string
                  creator:
                    type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: animal
          in: path
          required: true
          type: string
      tags:
        - Query
  /resource/resource/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  Farm:
    type: object
    properties:
      id:
        type: string
        format: uint64
      animal:
        type: string
      plant:
        type: string
      creator:
        type: string
  PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
      offset:
        type: string
        format: uint64
      limit:
        type: string
        format: uint64
      count_total:
        type: boolean
      reverse:
        type: boolean
  PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
      total:
        type: string
        format: uint64
  Params:
    type: object
  QueryAllFarmResponse:
    type: object
    properties:
      Farm:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              format: uint64
            animal:
              type: string
            plant:
              type: string
            creator:
              type: string
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
  QueryFindAnimalResponse:
    type: object
    properties:
      farm:
        type: object
        properties:
          id:
            type: string
            format: uint64
          animal:
            type: string
          plant:
            type: string
          creator:
            type: string
  QueryGetFarmResponse:
    type: object
    properties:
      Farm:
        type: object
        properties:
          id:
            type: string
            format: uint64
          animal:
            type: string
          plant:
            type: string
          creator:
            type: string
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  MsgCreateFarmResponse:
    type: object
    properties:
      id:
        type: string
        format: uint64
  MsgDeleteFarmResponse:
    type: object
  MsgUpdateFarmResponse:
    type: object
  MsgUpdateParamsResponse:
    type: object
